### ISSUE TITLE
Room 3 - Unable to get join table to populate but data appears to be associated together

### ISSUE THREAD

**Issue by sahmed7** [sahmed7/MusicApp#4]
We tried manually creating the songs and users within the main and it appears to take as we were able to retrieve the user's songlist.
I expected the song_user join table to be populated with the id of song and id of user.
The song_user join table is still appears to be empty.
My repo link is https://github.com/sahmed7/MusicApp 
 and my question is about

<img width="856" alt="Screen Shot 2021-04-13 at 2 57 38 PM" src="https://user-images.githubusercontent.com/14017530/114613166-98dbb700-9c68-11eb-9276-df34896fda76.png">

**Comment by sahmed7** [comment]
<img width="856" alt="Screen Shot 2021-04-13 at 3 11 22 PM" src="https://user-images.githubusercontent.com/14017530/114614740-8498b980-9c6a-11eb-8e09-c26c92ee8693.png">

pgAdmin still shows the join table to be empty. We're expecting the table to be populated by (song_id, user_id) association that was created in the main by the user1 and song1, song2, song3.

Should it not show up in that join table in pgAdmin or should it? I think it should much like the example suresh showed earlier

**Comment by bortiznine** [comment]
Did you make sure your models join your other models to link columns together? Would love to see that will check later

**Comment by sahmed7** [comment]
Thanks for the comment bortiznine. 

We had figured out the solution. The @JoinTable annotation was reversed in the models.
